---
title: "Icon Information"
---

- **Name:** EndNote (TODO)
  - **Organization:** [Clarivate](https://clarivate.com/)
  - **Website:** [EndNote Homepage](https://endnote.com/)
  - **Description:** EndNote is a paid citation manager from Clarivate.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/250>

- **Name:** ISSN
  - **Organization:** [The International Centre for the registration of serial publications – CIEPS](https://www.issn.org/the-centre-and-the-network/our-mission/the-international-centre-for-the-registration-of-serial-publications-cieps/)
  - **Website:** [ISSN Portal](https://portal.issn.org/)
  - **Description:** The International Standard Serial Number (ISSN) is an 8-digit code used to identify unambiguously newspapers, journals, magazines and periodicals of all kinds and on all media–print and digital.

- **Name:** MathSciNet
  - **Organization:** [American Mathematical Society](https://www.ams.org)
  - **Website:** [MathSciNet](https://www.ams.org/mathscinet/index.html)
  - **Description:** MathSciNet is a large, online bibliographic database for mathematical articles.

- **Name:** Wikipedia Library
  - **Organization:** [Wikimedia Foundation](https://wikimediafoundation.org/)
  - **Website:** [Wikipedia Library](https://wikipedialibrary.wmflabs.org/)
  - **Description:** Library of online scientific publishing platforms to help Wikipedians cite sources when contributing to Wikipedia.
  - **Notes:** 

- **Name:** Wikidata
  - **Organization:** [Wikimedia Foundation](https://wikimediafoundation.org/)
  - **Website:** [Wikidata Homepage](https://wikidata.org)
  - **Description:** Wikidata includes metadata of millions of scientific publications and can serve as a non-institutional and non-commercial repository. Wikidata has become the world's leading aggregator of persistent and open identifiers, serving as a bridge for projects involving linked open data.
  - **Notes:**

- **Name:** Perma.cc
  - **Organization:** []()
  - **Website:** [Perma.cc](https://perma.cc)
  - **Description:** Perma.cc is used to make permanent archives of web pages for academic citations.
  - **Notes:** 

- **Name:** CSAuthors.net
  - **Organization:** []()
  - **Website:** [CSAuthors.net](https://www.csauthors.net)
  - **Description:** A set of tools for those who want to explore computer scientist's bibliographies.
  - **Notes:** 

- **Name:** EcoEvoRxiv
  - **Organization:** [SORTEE: the Society for Open, Reliable, and Transparent Ecology and Evolutionary biology](https://sortee.org/)
  - **Website:** [EcoEvoRxiv Homepage](https://ecoevorxiv.org/)
  - **Description:** EcoEvoRxiv is a popular preprint repository for the Ecology and Evolution community.
  - **Notes:** 

- **Name:** CIÊNCIAVITAE
  - **Organization:** []()
  - **Website:** [CIÊNCIAVITAE](https://cienciavitae.pt)
  - **Description:** Facilitates the management of your scientific curriculum, enhancing your work visibility.
  - **Notes:** 

- **Name:** Harvard Catalyst
  - **Organization:** []()
  - **Website:** [Harvard Catalyst](https://catalyst.harvard.edu/)
  - **Description:** Harvard Catalyst catalyzes research across all clinical and translational domains by providing investigators with opportunities such as pilot funding, free resources such as biostatistics consultations, training and mentoring programs, and numerous courses.
  - **Notes:** 

- **Name:** Seamless Access
  - **Organization:** []()
  - **Website:** [Seamless Access](https://seamlessaccess.org/)
  - **Description:** A service designed to help foster a more streamlined online access experience when using scholarly collaboration tools, information resources, and shared research infrastructure
  - **Notes:** 

- **Name:** Estonian Research Information System
  - **Organization:** []()
  - **Website:** [Eesti Teadusinfosüsteem (ETIS)](https://www.etis.ee/)
  - **Description:** ETIS is used by Estonian researchers to maintain a CV/bibliography.
  - **Notes:** 

- **Name:** Pl@ntnet
  - **Organization:** []()
  - **Website:** [](https://plantnet.org/en/)
  - **Description:** Pl@ntNet is a citizen science project available as an app that helps you identify plants thanks to your pictures.
  - **Notes:** 

- **Name:** Global Biodiversity Information Facility (GBIF)
  - **Organization:** []()
  - **Website:** [GBIF Homepage](https://www.gbif.org/)
  - **Description:** The Global Biodiversity Information Facility is an international network and data infrastructure funded by the world's governments and aimed at providing anyone, anywhere, open access to data about all types of life on Earth.
  - **Notes:** 

- **Name:** OpenAlex
  - **Organization:** []()
  - **Website:** [OpenAlex Homepage](https://openalex.org)
  - **Description:** It's a bibliographic dataset like Scopus and Web of Science which we already have, but open data.
  - **Notes:** 

- **Name:** medRxiv (TODO)
  - **Organization:** []()
  - **Website:** [medRxiv](https://www.medrxiv.org)
  - **Description:** Preprint server (sister service to bioRxiv) for health sciences.
  - **Notes:** 

- **Name:** OSF Preregistered+ (TODO)
  - **Organization:** []()
  - **Website:** []()
  - **Description:** 
  - **Notes:** <https://osf.io/tvyxz/> All the icons are in an EPS file at https://osf.io/5fghy, including some Preregistered+ variants such as Preregistered+ TC. However, Preregistered+ alone is not in the EPS file. Bitmaps are available at https://osf.io/t5nuj and https://osf.io/2qcpx.

- - **Name:** ACL Anthology
  - **Organization:** []()
  - **Website:** [ACL Anthology](https://aclanthology.org/)
  - **Description:** Has collection of all peer-reviewed papers under ACL (NLP).
  - **Notes:** 

- **Name:** OpenReview
  - **Organization:** []()
  - **Website:** [](https://openreview.net/)
  - **Description:** The website is the primary destination to search for peer-reviewed publications.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/217>

- **Name:** iDiv
  - **Organization:** [Centre for Integrative Biodiversity Research (iDiv)](https://www.idiv.de/)
  - **Website:** [iDiv Homepage](https://www.idiv.de/)
  - **Description:** iDiv is an internationally renowned public research institute in Ecology. Members are encouraged to build personal websites for which an easily accessible icon would be very helpful.
  - **Notes:** 

- **Name:** Jeunes chercheurs associés
  - **Organization:** []()
  - **Website:** [Jeunes chercheurs associés](https://www.jca-groupe.fr/)
  - **Description:** Jeunes chercheurs associés is a technology transfer organisation. Young researchers can register to carry out missions.
  - **Notes:** 

- **Name:** IDEAS/RePEc (TODO)
  - **Organization:** []()
  - **Website:** [IDEAS](https://ideas.repec.org/)
  - **Description:** 
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/212>

- **Name:** Mathematics Genealogy Project (TODO)
  - **Organization:** []()
  - **Website:** [Mathematics Genealogy Project](https://www.mathgenealogy.org/index.php)
  - **Description:** 
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/211>

