---
title: "Requested Icons"
---

These are icons that have been requested.

- **Name:** IDEAS/RePEc
  - **Organization:** []()
  - **Website:** [IDEAS](https://ideas.repec.org/)
  - **Description:** 
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/212>

- **Name:** Mathematics Genealogy Project
  - **Organization:** []()
  - **Website:** [Mathematics Genealogy Project](https://www.mathgenealogy.org/index.php)
  - **Description:** 
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/211>

- **Name:** ISSN
  - **Organization:** [The International Centre for the registration of serial publications – CIEPS](https://www.issn.org/the-centre-and-the-network/our-mission/the-international-centre-for-the-registration-of-serial-publications-cieps/)
  - **Website:** [ISSN Portal](https://portal.issn.org/)
  - **Description:** The International Standard Serial Number (ISSN) is an 8-digit code used to identify unambiguously newspapers, journals, magazines and periodicals of all kinds and on all media–print and digital.
  - **Notes:** <

- **Name:** MathSciNet
  - **Organization:** [American Mathematical Society](https://www.ams.org)
  - **Website:** [MathSciNet](https://www.ams.org/mathscinet/index.html)
  - **Description:** MathSciNet is a large, online bibliographic database for mathematical articles.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/247>

- **Name:** Wikipedia Library
  - **Organization:** [Wikimedia Foundation](https://wikimediafoundation.org/)
  - **Website:** [Wikipedia Library](https://wikipedialibrary.wmflabs.org/)
  - **Description:** Library of online scientific publishing platforms to help Wikipedians cite sources when contributing to Wikipedia.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/249>

- **Name:** Wikidata
  - **Organization:** [Wikimedia Foundation](https://wikimediafoundation.org/)
  - **Website:** [Wikidata Homepage](https://wikidata.org)
  - **Description:** Wikidata includes metadata of millions of scientific publications and can serve as a non-institutional and non-commercial repository. Wikidata has become the world's leading aggregator of persistent and open identifiers, serving as a bridge for projects involving linked open data.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/248>

- **Name:** Perma.cc
  - **Organization:** []()
  - **Website:** [Perma.cc](https://perma.cc)
  - **Description:** Perma.cc is used to make permanent archives of web pages for academic citations.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/240>

- **Name:** CSAuthors.net
  - **Organization:** []()
  - **Website:** [CSAuthors.net](https://www.csauthors.net)
  - **Description:** A set of tools for those who want to explore computer scientist's bibliographies.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/239>

- **Name:** EcoEvoRxiv
  - **Organization:** [SORTEE: the Society for Open, Reliable, and Transparent Ecology and Evolutionary biology](https://sortee.org/)
  - **Website:** [EcoEvoRxiv Homepage](https://ecoevorxiv.org/)
  - **Description:** EcoEvoRxiv is a popular preprint repository for the Ecology and Evolution community.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/238>

- **Name:** CIÊNCIAVITAE
  - **Organization:** []()
  - **Website:** [CIÊNCIAVITAE](https://cienciavitae.pt)
  - **Description:** Facilitates the management of your scientific curriculum, enhancing your work visibility.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/235>

- **Name:** Harvard Catalyst
  - **Organization:** []()
  - **Website:** [Harvard Catalyst](https://catalyst.harvard.edu/)
  - **Description:** Harvard Catalyst catalyzes research across all clinical and translational domains by providing investigators with opportunities such as pilot funding, free resources such as biostatistics consultations, training and mentoring programs, and numerous courses.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/234>

- **Name:** Seamless Access
  - **Organization:** []()
  - **Website:** [Seamless Access](https://seamlessaccess.org/)
  - **Description:** A service designed to help foster a more streamlined online access experience when using scholarly collaboration tools, information resources, and shared research infrastructure
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/233>

- **Name:** Estonian Research Information System
  - **Organization:** []()
  - **Website:** [Eesti Teadusinfosüsteem (ETIS)](https://www.etis.ee/)
  - **Description:** ETIS is used by Estonian researchers to maintain a CV/bibliography.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/231>

- **Name:** Pl@ntnet
  - **Organization:** []()
  - **Website:** [](https://plantnet.org/en/)
  - **Description:** Pl@ntNet is a citizen science project available as an app that helps you identify plants thanks to your pictures.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/228>

- **Name:** Global Biodiversity Information Facility (GBIF)
  - **Organization:** []()
  - **Website:** [GBIF Homepage](https://www.gbif.org/)
  - **Description:** The Global Biodiversity Information Facility is an international network and data infrastructure funded by the world's governments and aimed at providing anyone, anywhere, open access to data about all types of life on Earth.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/227>

- **Name:** OpenAlex
  - **Organization:** []()
  - **Website:** [OpenAlex Homepage](https://openalex.org)
  - **Description:** It's a bibliographic dataset like Scopus and Web of Science which we already have, but open data.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/225>

- **Name:** ACL Anthology
  - **Organization:** []()
  - **Website:** [ACL Anthology](https://aclanthology.org/)
  - **Description:** Has collection of all peer-reviewed papers under ACL (NLP).
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/218>

- **Name:** OpenReview
  - **Organization:** []()
  - **Website:** [](https://openreview.net/)
  - **Description:** The website is the primary destination to search for peer-reviewed publications.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/217>

- **Name:** iDiv
  - **Organization:** [Centre for Integrative Biodiversity Research (iDiv)](https://www.idiv.de/)
  - **Website:** [iDiv Homepage](https://www.idiv.de/)
  - **Description:** iDiv is an internationally renowned public research institute in Ecology. Members are encouraged to build personal websites for which an easily accessible icon would be very helpful.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/214>

- **Name:** Jeunes chercheurs associés
  - **Organization:** []()
  - **Website:** [Jeunes chercheurs associés](https://www.jca-groupe.fr/)
  - **Description:** Jeunes chercheurs associés is a technology transfer organisation. Young researchers can register to carry out missions.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/213>

## Additional Work Required

- **Name:** OSF Preregistered+
  - **Organization:** []()
  - **Website:** []()
  - **Description:** 
  - **Notes:** <https://osf.io/tvyxz/> All the icons are in an EPS file at https://osf.io/5fghy, including some Preregistered+ variants such as Preregistered+ TC. However, Preregistered+ alone is not in the EPS file. Bitmaps are available at https://osf.io/t5nuj and https://osf.io/2qcpx.
    - <https://github.com/jpswalsh/academicons/issues/221>

- **Name:** medRxiv
  - **Organization:** []()
  - **Website:** [medRxiv](https://www.medrxiv.org)
  - **Description:** Preprint server (sister service to bioRxiv) for health sciences.
  - **Notes:** No SVG found, might need to convert
    - <https://github.com/jpswalsh/academicons/issues/224>

- **Name:** EndNote
  - **Organization:** [Clarivate](https://clarivate.com/)
  - **Website:** [EndNote Homepage](https://endnote.com/)
  - **Description:** EndNote is a paid citation manager from Clarivate.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/250>
    - No SVG found, might need to convert
    - 

- **Name:** Credly
  - **Organization:** []()
  - **Website:** [Credly Acclaim](https://info.credly.com/product/acclaim)
  - **Description:** 
  - **Notes:** Need to find the SVG

- **Name:** VDE
  - **Organization:** []()
  - **Website:** [VDE](https://www.vde.com/)
  - **Description:** VDE ist the German equivalent to IEEE which is already in the database. VDE is active in science, standards, and testing. Many (electrical) engineering standards are issued by VDE, as well as whitepapers on emerging technologies.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/210>

- **Name:** Huggingface
  - **Organization:** []()
  - **Website:** [Huggingface.co](https://huggingface.co)
  - **Description:** Massive repository for AI models, including hosted ML spaces. A pro icon in the fontawesome library is similar, but not the same.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/209>

- **Name:** IEEE Antennas and Propagation Society (APS)
  - **Organization:** []()
  - **Website:** [https://ieeeaps.org/](https://ieeeaps.org/)
  - **Description:** APS is an academic society like its parent IEEE and publishes papers, makes conferences and you can join it as a member.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/207>

- **Name:** GND
  - **Organization:** []()
  - **Website:** [https://gnd.network/](https://gnd.network/)
  - **Description:** The Integrated Authority File (GND) is a service facilitating the collaborative use and administration of authority data. These authority data represent and describe entities, i.e. persons, corporate bodies, conferences and events, geographic entities, topics and works relating to cultural and academic collections. Libraries in particular use the GND to catalogue publications. However, archives, museums, cultural and academic institutions, and researchers involved in research projects are also increasingly working with the GND. Authority data make cataloguing easier, offer definitive search entries and forge links between different information resources.
    - Every entity in the GND features a unique and stable identifier (GND ID). This makes it possible to link the authority data with both each other and external data sets and web resources. This results in a cross-organisational, machine-readable data network.
    - More information about the GND at https://gnd.network
    - (above information from: https://www.dnb.de/EN/Professionell/Standardisierung/GND/gnd_node.html)
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/204>

- **Name:** GrabCAD
  - **Organization:** []()
  - **Website:** [https://grabcad.com/](https://grabcad.com/)
  - **Description:** GrabCAD is a leading file sharing platform for engineers. It open sourcing of cad files and encourages cooperation. Over this side engineers can display their work and skills. The side also has an inbuilt freelancing system.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/203>

- **Name:** Bookbub
  - **Organization:** []()
  - **Website:** [https://bookbub.com/](https://bookbub.com/)
  - **Description:** Bookhub is a platform that helps authors promote their books. Certainly not relevant for all academics, but it could be for those who are (frequently) writing books for non-academics. It offers authors the possibility to make a public profile, e.g. https://www.bookbub.com/profile/debbie-macomber?list=author_books.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/199>

- **Name:** zbMATH (AKA Zentralblatt)
  - **Organization:** []()
  - **Website:** [https://zbmath.org/](https://zbmath.org/)
  - **Description:** Second most popular math publications database.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/197>

- **Name:** DataCamp
  - **Organization:** []()
  - **Website:** [https://www.datacamp.com/](https://www.datacamp.com/)
  - **Description:** DataCamp provides professional credentials for technical skills, and it'd be nice to have this icon available for resumes and the like since FontAwesome currently doesn't support it.
  - **Notes:** <https://github.com/jpswalsh/academicons/issues/195>